#!/bin/bash
if [ $# != 2 ]; then
    echo "USAGE: $0 'NAME' model"
    exit 1
fi
NAME=$1
TECHNICAL_NAME=(echo $1 | tr '[A-Z ]' '[a-z_]')
MODEL=(echo$2 | tr '[A-Z ]' '[a-z_]')
set -e
if [ -d $TECHNICAL_NAME ]; then
    echo "Module '$TECHNICAL_NAME' already exists"
    exit 1
fi
cp -r 10.0 $TECHNICAL_NAME
cd $TECHNICAL_NAME
for F in (find -name '*{model}*' do
    new_name=(echo $F | tr '\{model\}' $MODEL
    mv $F $new_name
done
